_wandb:
    value:
        cli_version: 0.25.1
        e:
            uae2s4u0n2t41ih2unsf1cvsa3gqmgob:
                args:
                    - --config
                    - configs/exp015_baseline.yaml
                    - --data_dir
                    - augmented_medium
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1000240963584"
                        used: "400572383232"
                email: simen.vanherpt@gmail.com
                executable: /Users/simen/Documents/Github/OPC/.venv/bin/python
                git:
                    commit: 6d20ed25e07762d63f165a3f77f2f78e9030b2a6
                    remote: https://github.com/svherpt/OPC.git
                host: jans-mbp.home
                memory:
                    total: "17179869184"
                os: macOS-10.16-x86_64-i386-64bit
                program: -m src.core.ml.train
                python: CPython 3.9.6
                root: /Users/simen/Documents/Github/OPC
                startedAt: "2026-03-30T08:29:34.287509Z"
                writerId: uae2s4u0n2t41ih2unsf1cvsa3gqmgob
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.9.6
            "5": 0.25.1
            "12": 0.25.1
            "13": darwin-x86_64
batch_size:
    value: 32
channels:
    value: 32
device:
    value: cpu
epochs:
    value: 2
illum_dim:
    value: 128
lambda_resist:
    value: 0.01
lr:
    value: 0.001
model:
    value: unet_film_v2
